# -*- coding: utf-8 -*-
"""BankingBot RAG Proj.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CusSieCcN9qBOU3Kn66DeUOzmYMmcK15
"""

!pip install langchain_core langchain_community langchain_text_splitters langchain_huggingface
!pip install faiss-gpu

import os
from openai import OpenAI
from google.colab import userdata

# LangChain Imports
from langchain_core.documents import Document
from langchain_community.document_loaders import WebBaseLoader, PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS


# ============================================================
# STEP 1: INGEST DATA FROM MULTIPLE SOURCES
# ============================================================

print("Step 1: Ingesting banking data from multiple sources...")

# ------------------------------------------------------------
# SOURCE A: HARDCODED BANKING INFORMATION
# ------------------------------------------------------------

raw_paragraphs = [

    "A savings account is a bank account designed for individuals to deposit, save, and withdraw money while earning applicable interest.",

    "Banks may provide services such as savings accounts, current accounts, fixed deposits, recurring deposits, debit cards, credit cards, personal loans, home loans, internet banking, and mobile banking.",

    "Customers should never share sensitive authentication information such as OTPs, PINs, CVVs, passwords, or full card and account credentials with anyone, including a chatbot.",

    "For security and privacy, a banking chatbot must not request, store, expose, or process customers' confidential credentials or complete financial account details.",

    "For account-specific issues such as checking an account balance, viewing transaction history, changing a PIN, blocking a card, or transferring money, customers should use the bank's official authenticated banking channels or contact the bank directly.",

    "Customers should be cautious of phishing messages, fraudulent calls, fake websites, and unknown links requesting banking credentials or personal information.",

    "Banks may offer digital banking services through official mobile applications and internet banking platforms.",

    "Customers should verify that they are using the official website or mobile application of their bank before entering any personal or financial information."
]

# Convert raw Python strings into LangChain Document objects
text_documents = [
    Document(page_content=text)
    for text in raw_paragraphs
]


# ------------------------------------------------------------
# SOURCE B: WEB SOURCES
# ------------------------------------------------------------

print("Loading banking information from official websites...")

urls = [
    "https://www.rbi.org.in/",
    "https://sbi.co.in/"
]

try:
    web_loader = WebBaseLoader(urls)
    web_documents = web_loader.load()
    print("Web sources loaded successfully.")
except Exception as e:
    print(f"Warning: Could not load web sources. {e}")
    web_documents = []


# ------------------------------------------------------------
# SOURCE C: PDF DOCUMENT
# ------------------------------------------------------------

pdf_path = "CIT_BROCHURE.pdf"

try:

    pdf_loader = PyPDFLoader(pdf_path)
    pdf_documents = pdf_loader.load()

    print("PDF loaded successfully.")

except Exception as e:

    print(f"Warning: PDF '{pdf_path}' not found in Colab.")
    print("Skipping PDF ingestion.")

    pdf_documents = []


# ------------------------------------------------------------
# MERGE ALL SOURCES
# ------------------------------------------------------------

all_documents = (
    text_documents
    + web_documents
    + pdf_documents
)

print(
    f"Total raw pages/documents loaded: "
    f"{len(all_documents)}"
)


# ============================================================
# STEP 2: DATA CHUNKING
# ============================================================

print("\nStep 2: Splitting data into searchable chunks...")

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50
)

chunks = text_splitter.split_documents(
    all_documents
)

print(
    f"Data chopped into {len(chunks)} searchable chunks."
)


# ============================================================
# STEP 3: EMBEDDINGS & FAISS VECTOR DATABASE
# ============================================================

print("\nStep 3: Building FAISS Vector Database...")

embeddings = HuggingFaceEmbeddings(
    model_name="all-MiniLM-L6-v2"
)

vector_db = FAISS.from_documents(
    chunks,
    embeddings
)

print("FAISS Vector Database created successfully.")


# ============================================================
# STEP 4: INITIALIZE LLM
# ============================================================

print("\nStep 4: Connecting to AI model...")

client = OpenAI(
    base_url="https://api.groq.com/openai/v1",
    api_key=userdata.get("Project")
)

print("AI model connected successfully.")


# ============================================================
# STEP 5: BANKING CHATBOT
# ============================================================

print("\n" + "=" * 60)
print("🏦 PRIVACY-AWARE BANKING CHATBOT ONLINE")
print("=" * 60)

print("You can ask about:")
print("- Banking products")
print("- Savings and current accounts")
print("- Loans")
print("- Deposits")
print("- Debit and credit cards")
print("- Digital banking")
print("- Banking security")
print("- General banking procedures")
print("\nType 'exit' to end the conversation.")

print("-" * 60)


# ============================================================
# STEP 6: CHAT LOOP
# ============================================================

while True:

    user_query = input("\nYou: ")

    # Exit condition
    if user_query.lower().strip() == "exit":
        print("\nBanking chatbot session ended.")
        break


    # --------------------------------------------------------
    # BASIC PRIVACY CHECK
    # --------------------------------------------------------

    sensitive_keywords = [
        "otp",
        "one time password",
        "pin",
        "cvv",
        "password",
        "card number",
        "account number",
        "upi pin",
        "net banking password",
        "debit card number",
        "credit card number"
    ]

    contains_sensitive_request = any(
        keyword in user_query.lower()
        for keyword in sensitive_keywords
    )


    # --------------------------------------------------------
    # IF USER IS ASKING FOR SENSITIVE INFORMATION
    # --------------------------------------------------------

    if contains_sensitive_request:

        # We still allow general educational questions
        # but prevent the chatbot from requesting credentials.

        if any(
            phrase in user_query.lower()
            for phrase in [
                "what is",
                "what are",
                "why",
                "how does",
                "meaning",
                "explain",
                "difference"
            ]
        ):
            pass

        else:

            print(
                "\nAI: For your security, please do not share "
                "OTPs, PINs, CVVs, passwords, full card numbers, "
                "account numbers, or other confidential banking "
                "credentials with me. Please use your bank's "
                "official authenticated banking channel for "
                "account-specific assistance."
            )

            continue


    # --------------------------------------------------------
    # SEMANTIC SEARCH
    # --------------------------------------------------------

    relevant_chunks = vector_db.similarity_search(
        user_query,
        k=3
    )

    retrieved_context = "\n\n".join(
        [
            doc.page_content
            for doc in relevant_chunks
        ]
    )


    # ========================================================
    # PRIVACY-AWARE SYSTEM PROMPT
    # ========================================================

    system_prompt = f"""
You are a secure and privacy-aware AI banking information assistant.

You are powered by a multi-source banking knowledge base.

Your job is to provide GENERAL banking information using ONLY
the context provided below.

You must strictly follow these privacy and security rules.

------------------------------------------------------------
PRIVACY AND SECURITY RULES
------------------------------------------------------------

1. NEVER ask the user for sensitive personal or banking information.

2. NEVER request, collect, store, reveal, or process:

   - OTPs
   - PINs
   - CVVs
   - Passwords
   - UPI PINs
   - Net banking passwords
   - Debit card numbers
   - Credit card numbers
   - Bank account numbers
   - Aadhaar numbers
   - PAN numbers
   - Security questions or answers
   - Any other confidential authentication credentials

3. If the user accidentally provides sensitive information,
   DO NOT repeat it back.

4. If the user provides sensitive information, tell them:

   "Please do not share sensitive banking credentials such as
   OTPs, PINs, CVVs, passwords, or complete card/account
   information. For your security, please use your bank's
   official authenticated channel."

5. Never attempt to access or retrieve:

   - Customer account balances
   - Transaction history
   - Personal banking records
   - Credit information
   - Account credentials
   - Private customer information

6. You may explain GENERAL banking concepts and procedures.

7. For account-specific actions such as:

   - Checking account balance
   - Viewing transactions
   - Transferring money
   - Changing PIN
   - Blocking a card
   - Updating account information
   - Resetting banking credentials

   direct the user to the bank's official authenticated
   banking application, website, branch, or customer support.

8. Never ask the user to upload screenshots containing
   personal banking information.

9. Never guess or fabricate:

   - Interest rates
   - Fees
   - Charges
   - Eligibility criteria
   - Transaction limits
   - Banking policies
   - Loan terms
   - Account requirements

10. Answer ONLY using the provided context.

11. If the answer cannot be found in the provided context,
    respond:

    "I do not have enough information to answer that.
    Please check the bank's official website or contact
    the bank directly."

12. Never simulate a real financial transaction.

13. Never claim that you have accessed a user's bank account.

14. Treat all customer information as confidential.

15. Follow the principle of data minimization:
    only use information necessary to answer the question.

------------------------------------------------------------
CONTEXT FROM KNOWLEDGE BASE
------------------------------------------------------------

{retrieved_context}

------------------------------------------------------------
END OF CONTEXT
------------------------------------------------------------
"""


    # ========================================================
    # CALL LLM
    # ========================================================

    try:

        response = client.chat.completions.create(

            model="openai/gpt-oss-120b",

            messages=[
                {
                    "role": "system",
                    "content": system_prompt
                },
                {
                    "role": "user",
                    "content": user_query
                }
            ],

            temperature=0.0
        )


        # ----------------------------------------------------
        # DISPLAY RESPONSE
        # ----------------------------------------------------

        answer = response.choices[0].message.content

        print(f"\nAI: {answer}")


    except Exception as e:

        print(
            "\nAI: Sorry, I was unable to process your request."
        )

        print(f"Error: {e}")