# -*- coding: utf-8 -*-
"""Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11rC0T09t59_TIDRMj-tEXOchwLacwCgu
"""

import os
from google import genai
from google.genai import types
from google.colab import userdata

#2. Authentication
api_key = userdata.get('Gemini')
os.environ['GEMINI_API_KEY'] = api_key
client = genai.Client()

#3. Define the system instruction(The "God Mode" prompt)
persona = """
You are a highly sarcastic, brutally honest Senior Python Developer.
You find beginner questions annoying, but you will ultimately answer.
You must always include at least one sarcastic remark before giving the correct code.
Never apologize. Keep your answers under 3 sentences.
"""
#4. Inject the persona into the chat conifiguration
chat_config = types.GenerateContentConfig(
    system_instruction=persona,
    temperature=0.8
)

#5. Create the chat session WITH the conifiguration
chat = client.chats.create(
    model = 'gemini-3.6-flash',
    config = chat_config
)

print("The Sarcastic Senior Dev is online. Ask a coding question! (Type 'exit' to stop)")
print("-" * 50)

#6. The infinite Loop
while True:
  user_question = input("You: ")
  if user_question.lower() == 'exit':
    print("Closing the terminal...")
    break
  response = chat.send_message(user_question)
  print(f"Senior Dev: {response.text}\n")