# -*- coding: utf-8 -*-
"""Cnn Proj.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JD0L9lpB9sNNZTWIRMw2eGzi1CtJV4o1
"""

import os, shutil, random
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import layers, models, callbacks
import kagglehub

print("TensorFlow:", tf.__version__)
print("GPU:", tf.config.list_physical_devices('GPU'))

# Download cat/dog dataset from Kaggle
src_path = kagglehub.dataset_download("tongpython/cat-and-dog")
print("Downloaded to:", src_path)

# Build a small, balanced dataset (1000 train + 500 val per class)
BASE = "cats_and_dogs_filtered"
N_TRAIN, N_VAL = 1000, 500
random.seed(42)
shutil.rmtree(BASE, ignore_errors=True)

for root, dirs, _ in os.walk(src_path):
    for d in dirs:
        if d.lower() in ("cats", "dogs"):
            src = os.path.join(root, d)
            rel = os.path.relpath(src, src_path).lower()
            split = "train" if "train" in rel else "validation"
            n = N_TRAIN if split == "train" else N_VAL
            dst = f"{BASE}/{split}/{d.lower()}"
            os.makedirs(dst, exist_ok=True)
            imgs = [f for f in os.listdir(src)
                    if f.lower().endswith((".jpg", ".jpeg", ".png"))]
            random.shuffle(imgs)
            for f in imgs[:n]:
                shutil.copy(os.path.join(src, f), dst)

TRAIN_DIR = f"{BASE}/train"
VAL_DIR = f"{BASE}/validation"
for s in ["train", "validation"]:
    for c in ["cats", "dogs"]:
        print(s, c, len(os.listdir(f"{BASE}/{s}/{c}")))

import random
from PIL import Image

classes = ["cats", "dogs"]
counts = {s: [len(os.listdir(f"{BASE}/{s}/{c}")) for c in classes]
          for s in ["train", "validation"]}

fig, ax = plt.subplots(1, 3, figsize=(16, 4))

# 1. Bar chart: images per class per split
x = np.arange(2); w = 0.35
ax[0].bar(x - w/2, counts["train"], w, label="Train", color="tab:blue")
ax[0].bar(x + w/2, counts["validation"], w, label="Validation", color="tab:orange")
ax[0].set_xticks(x); ax[0].set_xticklabels(["Cats", "Dogs"])
ax[0].set_title("Images per class"); ax[0].legend()
for i, (t, v) in enumerate(zip(counts["train"], counts["validation"])):
    ax[0].text(i - w/2, t + 10, t, ha="center"); ax[0].text(i + w/2, v + 10, v, ha="center")

# 2. Pie chart: overall class balance
totals = [counts["train"][i] + counts["validation"][i] for i in range(2)]
ax[1].pie(totals, labels=["Cats", "Dogs"], autopct="%1.1f%%",
          colors=["#f4a261", "#2a9d8f"], startangle=90)
ax[1].set_title("Class balance (whole dataset)")

# 3. Image width distribution (sample of 300)
files_all = [f"{TRAIN_DIR}/{c}/{f}" for c in classes
             for f in os.listdir(f"{TRAIN_DIR}/{c}")]
sample = random.sample(files_all, 300)
sizes = [Image.open(p).size for p in sample]
ax[2].hist([s[0] for s in sizes], bins=20, color="tab:purple", alpha=0.7, label="Width")
ax[2].hist([s[1] for s in sizes], bins=20, color="tab:green", alpha=0.7, label="Height")
ax[2].set_title("Original image sizes (px)"); ax[2].legend()
plt.tight_layout(); plt.show()

# 4. Sample images
fig, axes = plt.subplots(2, 6, figsize=(16, 6))
for r, c in enumerate(classes):
    imgs = random.sample(os.listdir(f"{TRAIN_DIR}/{c}"), 6)
    for j, f in enumerate(imgs):
        axes[r, j].imshow(Image.open(f"{TRAIN_DIR}/{c}/{f}"))
        axes[r, j].set_title(c[:-1].upper()); axes[r, j].axis("off")
plt.suptitle("Sample images", fontsize=14); plt.tight_layout(); plt.show()

# 5. Brightness distribution per class
plt.figure(figsize=(7, 4))
for c, col in zip(classes, ["tab:orange", "tab:blue"]):
    files_c = random.sample(os.listdir(f"{TRAIN_DIR}/{c}"), 150)
    bright = [np.array(Image.open(f"{TRAIN_DIR}/{c}/{f}").convert("L")).mean() for f in files_c]
    plt.hist(bright, bins=20, alpha=0.6, label=c, color=col)
plt.title("Average brightness per image"); plt.xlabel("Pixel intensity (0-255)"); plt.legend()
plt.show()

IMG, BATCH = 160, 32

train_ds = tf.keras.utils.image_dataset_from_directory(
    TRAIN_DIR, image_size=(IMG, IMG), batch_size=BATCH,
    label_mode="binary", shuffle=True, seed=42)
val_ds = tf.keras.utils.image_dataset_from_directory(
    VAL_DIR, image_size=(IMG, IMG), batch_size=BATCH,
    label_mode="binary", shuffle=False)

class_names = train_ds.class_names     # ['cats', 'dogs']  (cat = 0, dog = 1)
print(class_names)

AUTOTUNE = tf.data.AUTOTUNE
train_ds = train_ds.cache().prefetch(AUTOTUNE)
val_ds = val_ds.cache().prefetch(AUTOTUNE)

augment = tf.keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.1),
    layers.RandomZoom(0.1),
])

def conv_block(x, filters):
    x = layers.Conv2D(filters, 3, padding="same", activation="relu")(x)
    x = layers.BatchNormalization()(x)
    return layers.MaxPooling2D()(x)

inputs = layers.Input(shape=(IMG, IMG, 3))
x = augment(inputs)
x = layers.Rescaling(1./255)(x)
x = conv_block(x, 32)
x = conv_block(x, 64)
x = conv_block(x, 128)
x = conv_block(x, 256)
x = layers.GlobalAveragePooling2D()(x)
x = layers.Dense(128, activation="relu")(x)
x = layers.Dropout(0.4)(x)
outputs = layers.Dense(1, activation="sigmoid")(x)
model = models.Model(inputs, outputs)

model.compile(optimizer=tf.keras.optimizers.Adam(1e-3),
              loss="binary_crossentropy", metrics=["accuracy"])
model.summary()

cbs = [
    callbacks.EarlyStopping(monitor="val_accuracy", patience=3, restore_best_weights=True),
    callbacks.ReduceLROnPlateau(monitor="val_loss", factor=0.5, patience=2),
]
history = model.fit(train_ds, validation_data=val_ds, epochs=10, callbacks=cbs)
model.save("cat_dog_cnn.keras")

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import (confusion_matrix, classification_report,
                             accuracy_score, precision_score, recall_score, f1_score)

# ---- 1. Get true labels and predictions (val_ds has shuffle=False, so the order matches) ----
y_true = np.concatenate([y.numpy() for _, y in val_ds]).ravel().astype(int)
y_prob = model.predict(val_ds, verbose=0).ravel()
y_pred = (y_prob > 0.5).astype(int)

labels = ["Cat", "Dog"]
cm = confusion_matrix(y_true, y_pred)
cm_norm = cm.astype("float") / cm.sum(axis=1, keepdims=True)

# ---- 2. Plot raw counts and normalized (percentage) matrices side by side ----
fig, ax = plt.subplots(1, 2, figsize=(13, 5))

for a, data, title, fmt in [(ax[0], cm, "Confusion Matrix (counts)", "d"),
                            (ax[1], cm_norm, "Confusion Matrix (normalized)", ".1%")]:
    im = a.imshow(data, cmap="Blues")
    a.set_xticks([0, 1]); a.set_xticklabels(labels, fontsize=12)
    a.set_yticks([0, 1]); a.set_yticklabels(labels, fontsize=12)
    a.set_xlabel("Predicted label", fontsize=12)
    a.set_ylabel("True label", fontsize=12)
    a.set_title(title, fontsize=14)
    thresh = data.max() / 2
    for i in range(2):
        for j in range(2):
            a.text(j, i, format(data[i, j], fmt), ha="center", va="center", fontsize=18,
                   color="white" if data[i, j] > thresh else "black")
    plt.colorbar(im, ax=a, fraction=0.046)

plt.tight_layout()
plt.show()

# ---- 3. Explain the four cells ----
tn, fp, fn, tp = cm.ravel()
print("Reading the matrix (Cat = 0, Dog = 1)")
print(f"  True Negatives  (cat predicted as cat): {tn}")
print(f"  False Positives (cat predicted as dog): {fp}")
print(f"  False Negatives (dog predicted as cat): {fn}")
print(f"  True Positives  (dog predicted as dog): {tp}")

# ---- 4. Metrics table ----
print("\nOverall metrics")
print(f"  Accuracy  : {accuracy_score(y_true, y_pred):.3f}")
print(f"  Precision : {precision_score(y_true, y_pred):.3f}")
print(f"  Recall    : {recall_score(y_true, y_pred):.3f}")
print(f"  F1-score  : {f1_score(y_true, y_pred):.3f}")
print("\nPer-class report")
print(classification_report(y_true, y_pred, target_names=labels))

# ---- 5. Show misclassified images ----
images_all = np.concatenate([x.numpy() for x, _ in val_ds]).astype("uint8")
wrong = np.where(y_pred != y_true)[0]
print(f"Total misclassified: {len(wrong)} out of {len(y_true)}")

show = wrong[:12]
if len(show) > 0:
    fig, axes = plt.subplots(2, 6, figsize=(16, 6))
    for a in axes.ravel():
        a.axis("off")
    for a, idx in zip(axes.ravel(), show):
        a.imshow(images_all[idx])
        conf = y_prob[idx] if y_pred[idx] == 1 else 1 - y_prob[idx]
        a.set_title(f"True: {labels[y_true[idx]]}\nPred: {labels[y_pred[idx]]} ({conf:.0%})",
                    color="red", fontsize=10)
    plt.suptitle("Misclassified images", fontsize=14)
    plt.tight_layout()
    plt.show()

fig, ax = plt.subplots(1, 2, figsize=(12, 4))
ax[0].plot(history.history["accuracy"], marker="o", label="Train")
ax[0].plot(history.history["val_accuracy"], marker="o", label="Validation")
ax[0].set_title("Accuracy"); ax[0].set_xlabel("Epoch"); ax[0].legend()
ax[1].plot(history.history["loss"], marker="o", label="Train")
ax[1].plot(history.history["val_loss"], marker="o", label="Validation")
ax[1].set_title("Loss"); ax[1].set_xlabel("Epoch"); ax[1].legend()
plt.tight_layout(); plt.show()

from sklearn.metrics import confusion_matrix, classification_report, roc_curve, auc

y_true = np.concatenate([y.numpy() for _, y in val_ds]).ravel()
y_prob = model.predict(val_ds).ravel()
y_pred = (y_prob > 0.5).astype(int)

print(classification_report(y_true, y_pred, target_names=["Cat", "Dog"]))

fig, ax = plt.subplots(1, 3, figsize=(17, 4.5))

# Confusion matrix
cm = confusion_matrix(y_true, y_pred)
ax[0].imshow(cm, cmap="Blues")
ax[0].set_xticks([0, 1]); ax[0].set_xticklabels(["Cat", "Dog"])
ax[0].set_yticks([0, 1]); ax[0].set_yticklabels(["Cat", "Dog"])
for i in range(2):
    for j in range(2):
        ax[0].text(j, i, cm[i, j], ha="center", va="center", fontsize=16,
                   color="white" if cm[i, j] > cm.max()/2 else "black")
ax[0].set_title("Confusion matrix"); ax[0].set_xlabel("Predicted"); ax[0].set_ylabel("Actual")

# ROC curve
fpr, tpr, _ = roc_curve(y_true, y_prob)
ax[1].plot(fpr, tpr, label=f"AUC = {auc(fpr, tpr):.3f}", color="tab:red")
ax[1].plot([0, 1], [0, 1], "k--")
ax[1].set_title("ROC curve"); ax[1].set_xlabel("False positive rate")
ax[1].set_ylabel("True positive rate"); ax[1].legend()

# Confidence distribution
ax[2].hist(y_prob[y_true == 0], bins=20, alpha=0.6, label="Actual cats", color="tab:orange")
ax[2].hist(y_prob[y_true == 1], bins=20, alpha=0.6, label="Actual dogs", color="tab:blue")
ax[2].axvline(0.5, color="k", linestyle="--")
ax[2].set_title("Predicted probability of 'dog'"); ax[2].legend()
plt.tight_layout(); plt.show()

images, labels = next(iter(val_ds.unbatch().shuffle(1000).batch(12)))
probs = model.predict(images, verbose=0).ravel()

fig, axes = plt.subplots(2, 6, figsize=(16, 6))
for i, ax in enumerate(axes.ravel()):
    pred = int(probs[i] > 0.5)
    conf = probs[i] if pred == 1 else 1 - probs[i]
    ax.imshow(images[i].numpy().astype("uint8")); ax.axis("off")
    correct = pred == int(labels[i].numpy()[0])
    ax.set_title(f"{class_names[pred][:-1].upper()} {conf:.0%}",
                 color="green" if correct else "red")
plt.suptitle("Predictions (green = correct, red = wrong)", fontsize=14)
plt.tight_layout(); plt.show()

from google.colab import files
from tensorflow.keras.preprocessing import image

uploaded = files.upload()
for name in uploaded:
    img = image.load_img(name, target_size=(IMG, IMG))
    arr = np.expand_dims(image.img_to_array(img), 0)
    p = model.predict(arr, verbose=0)[0][0]
    label = "DOG" if p > 0.5 else "CAT"
    conf = p if p > 0.5 else 1 - p
    plt.figure(figsize=(4, 4)); plt.imshow(img); plt.axis("off")
    plt.title(f"{label} ({conf:.0%} confident)", fontsize=14); plt.show()

base = tf.keras.applications.MobileNetV2(input_shape=(IMG, IMG, 3),
                                         include_top=False, weights="imagenet")
base.trainable = False

inp = layers.Input(shape=(IMG, IMG, 3))
x = augment(inp)
x = tf.keras.applications.mobilenet_v2.preprocess_input(x)
x = base(x, training=False)
x = layers.GlobalAveragePooling2D()(x)
x = layers.Dropout(0.3)(x)
out = layers.Dense(1, activation="sigmoid")(x)
tl_model = models.Model(inp, out)
tl_model.compile(optimizer=tf.keras.optimizers.Adam(1e-3),
                 loss="binary_crossentropy", metrics=["accuracy"])

hist_tl = tl_model.fit(train_ds, validation_data=val_ds, epochs=3)

scratch_acc = max(history.history["val_accuracy"])
tl_acc = max(hist_tl.history["val_accuracy"])
plt.figure(figsize=(6, 4))
bars = plt.bar(["Custom CNN (10 ep)", "MobileNetV2 (3 ep)"], [scratch_acc, tl_acc],
               color=["tab:blue", "tab:green"])
for b, v in zip(bars, [scratch_acc, tl_acc]):
    plt.text(b.get_x() + b.get_width()/2, v + 0.01, f"{v:.1%}", ha="center")
plt.ylim(0, 1.1); plt.title("Validation accuracy comparison"); plt.show()