# -*- coding: utf-8 -*-
"""Cot Langgraph LLM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AcSTbjWE3A35cJUmFuOTT3dOd_sLFzvs
"""

!pip install -q langgraph langchain-groq langchain-core

import os, re, getpass
from typing import TypedDict, Literal
from groq import Groq
from langchain_groq import ChatGroq
from langchain_core.messages import SystemMessage, HumanMessage

# Option 1: your Colab secret (your secret is named "Project"). Falls back to typing the key.
try:
    from google.colab import userdata
    key = userdata.get("Project").strip()
except Exception:
    key = getpass.getpass("Enter your Groq API key: ").strip()
os.environ["GROQ_API_KEY"] = key

# Ask Groq which models this key can actually use
available = [m.id for m in Groq().models.list().data]
print("Models available to you:")
for m in available:
    print("  -", m)

# Pick the first preferred chat model that exists (skips whisper/tts/guard models)
preferred = ["llama-3.3-70b-versatile", "openai/gpt-oss-120b",
             "llama-3.1-8b-instant", "openai/gpt-oss-20b"]
MODEL = next((m for m in preferred if m in available), None)
if MODEL is None:
    MODEL = next(m for m in available
                 if not any(x in m.lower() for x in ["whisper", "tts", "guard", "prompt-guard", "embed"]))
print("\nUsing model:", MODEL)

llm = ChatGroq(model=MODEL, temperature=0)

def ask(system_prompt: str, user_prompt: str) -> str:
    resp = llm.invoke([SystemMessage(content=system_prompt), HumanMessage(content=user_prompt)])
    return resp.content.strip()

# Quick test
print(ask("You are a helpful assistant.", "Say hello in one short sentence."))

class AgentState(TypedDict):
    question: str    # user's question
    category: str    # math | concept | code
    reasoning: str   # chain-of-thought steps from the solver
    answer: str      # final answer from the solver
    verdict: str     # PASS | FAIL from the verifier
    feedback: str    # verifier's comments, fed back to the solver on retry
    attempts: int    # how many times a solver has run
    final: str       # formatted output shown to the user

MAX_ATTEMPTS = 2

CLASSIFY_PROMPT = """You are a question classifier for a student doubt-solving app.
Think step by step:
1. Identify what the student is actually asking.
2. Look for clues: numbers/equations/calculations -> math; "explain/what is/why/difference" -> concept; code/programming/bug/syntax -> code.
3. Decide the single best category.
Write your steps briefly, then end with exactly one last line:
CATEGORY: math   (or concept, or code)"""

SOLVER_BASE = """You are an expert tutor. {style}
Use chain-of-thought: think step by step and write each step as a numbered line.
Format your reply EXACTLY like this:
REASONING:
1. ...
2. ...
FINAL ANSWER:
<clear, concise answer for a college student>"""

STYLES = {
    "math": "You solve math, aptitude and numerical problems. Show every calculation and double-check arithmetic.",
    "concept": "You explain theory and concepts simply, with a short real-world example or analogy.",
    "code": "You solve programming questions. Explain the logic first, then give correct, runnable code in a code block.",
}

VERIFY_PROMPT = """You are a strict reviewer checking a tutor's work.
Think step by step: re-read the question, check each numbered reasoning step for errors,
then check whether the final answer follows from the steps and truly answers the question.
Write 2-4 short lines of feedback, then end with exactly one last line:
VERDICT: PASS   (or VERDICT: FAIL)"""

def classify_node(state: AgentState):
    text = ask(CLASSIFY_PROMPT, state["question"])
    m = re.search(r"CATEGORY:\s*(math|concept|code)", text, re.I)
    category = m.group(1).lower() if m else "concept"   # safe default
    return {"category": category, "attempts": 0, "feedback": ""}

def make_solver(category: str):
    """Factory: builds one solver node per category, each with its own CoT prompt."""
    def solver_node(state: AgentState):
        user = f"Question: {state['question']}"
        if state["feedback"]:
            user += f"\n\nA reviewer found problems with your previous attempt:\n{state['feedback']}\nFix them."
        text = ask(SOLVER_BASE.format(style=STYLES[category]), user)
        reasoning, _, answer = text.partition("FINAL ANSWER:")
        return {
            "reasoning": reasoning.replace("REASONING:", "").strip(),
            "answer": answer.strip() or text,
            "attempts": state["attempts"] + 1,
        }
    return solver_node

math_solver = make_solver("math")
concept_solver = make_solver("concept")
code_solver = make_solver("code")

def verify_node(state: AgentState):
    user = (f"Question: {state['question']}\n\nTutor's reasoning:\n{state['reasoning']}\n\n"
            f"Tutor's final answer:\n{state['answer']}")
    text = ask(VERIFY_PROMPT, user)
    m = re.search(r"VERDICT:\s*(PASS|FAIL)", text, re.I)
    verdict = m.group(1).upper() if m else "PASS"
    feedback = re.sub(r"VERDICT:.*", "", text, flags=re.I | re.S).strip()
    return {"verdict": verdict, "feedback": feedback}

def finalize_node(state: AgentState):
    note = ""
    if state["verdict"] == "FAIL":
        note = "\n\n(Note: the self-check still had doubts after the maximum retries, so please double-check this answer.)"
    final = (f"Category : {state['category'].upper()}\n"
             f"Attempts : {state['attempts']}   |   Verified: {state['verdict']}\n\n"
             f"--- Reasoning ---\n{state['reasoning']}\n\n"
             f"--- Answer ---\n{state['answer']}{note}")
    return {"final": final}

def route_after_classify(state: AgentState) -> str:
    """Decide which solver node runs next, based on the category in the state."""
    return f"{state['category']}_solver"

def route_after_verify(state: AgentState) -> str:
    """Pass, or out of retries -> finalize. Otherwise loop back to the same solver."""
    if state["verdict"] == "PASS" or state["attempts"] >= MAX_ATTEMPTS:
        return "finalize"
    return f"{state['category']}_solver"

from langgraph.graph import StateGraph, START, END

builder = StateGraph(AgentState)

builder.add_node("classify", classify_node)
builder.add_node("math_solver", math_solver)
builder.add_node("concept_solver", concept_solver)
builder.add_node("code_solver", code_solver)
builder.add_node("verify", verify_node)
builder.add_node("finalize", finalize_node)

builder.add_edge(START, "classify")
builder.add_conditional_edges("classify", route_after_classify,
                              ["math_solver", "concept_solver", "code_solver"])
for s in ["math_solver", "concept_solver", "code_solver"]:
    builder.add_edge(s, "verify")
builder.add_conditional_edges("verify", route_after_verify,
                              ["math_solver", "concept_solver", "code_solver", "finalize"])
builder.add_edge("finalize", END)

app = builder.compile()

# Draw the graph (great for your report and viva)
from IPython.display import Image, display
try:
    display(Image(app.get_graph().draw_mermaid_png()))
except Exception:
    print(app.get_graph().draw_mermaid())   # paste this at mermaid.live to see the diagram

def ask_app(question: str):
    state = {"question": question, "category": "", "reasoning": "", "answer": "",
             "verdict": "", "feedback": "", "attempts": 0, "final": ""}
    print("Workflow trace:")
    for step in app.stream(state, stream_mode="updates"):
        for node, update in step.items():
            extra = ""
            if node == "classify": extra = f" -> category = {update['category']}"
            if node == "verify":   extra = f" -> verdict = {update['verdict']}"
            print(f"  ➡ {node}{extra}")
            state.update(update)
    print("\n" + "=" * 60)
    print(state["final"])

ask_app("A train travels 240 km in 4 hours. If it speeds up by 20 km/h, how long will it take to cover 360 km?")

ask_app("What is the difference between a process and a thread?")
ask_app("Write a Python function to check whether a string is a palindrome.")