# -*- coding: utf-8 -*-
"""COT 3 LLMs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12DDY_-KBTv848Vgf8TSN3dSd91vIqaaC
"""

!pip install -q langgraph langchain-groq langchain-core matplotlib

!pip install -q google-api-python-client google-auth-oauthlib google-auth-httplib2

import os, re, time, random, getpass
from typing import TypedDict, Annotated
from groq import Groq, BadRequestError
from langchain_groq import ChatGroq
from langchain_core.messages import SystemMessage, HumanMessage

try:
    from google.colab import userdata
    key = userdata.get("Project").strip()      # change "Project" to your secret's name
except Exception:
    key = getpass.getpass("Enter your Groq API key (starts with gsk_): ").strip()
os.environ["GROQ_API_KEY"] = key

available = [m.id for m in Groq().models.list().data]
skip = ["whisper", "tts", "guard", "embed", "orpheus", "playai"]   # not chat models
chat_models = [m for m in available if not any(x in m.lower() for x in skip)]
print("Chat models available:", chat_models)

# Pick three DIFFERENT models (first available from each list that is not already used)
prefs = {
    1: ["openai/gpt-oss-120b", "llama-3.3-70b-versatile"],
    2: ["qwen/qwen3.8-27b", "allam-2-7b", "llama-3.1-8b-instant"],
    3: ["openai/gpt-oss-20b", "llama-3.1-8b-instant"],
}
MODELS = {}
for n in [1, 2, 3]:
    choice = next((m for m in prefs[n] if m in chat_models and m not in MODELS.values()), None)
    if choice is None:   # fallback: any chat model not used yet
        choice = next((m for m in chat_models if m not in MODELS.values()), chat_models[0])
    MODELS[n] = choice

LLMS = {n: ChatGroq(model=m, temperature=0.2) for n, m in MODELS.items()}
for n, m in MODELS.items():
    print(f"LLM {n}: {m}")

def salvage(err):
    """Recover the text from a gpt-oss 'tool_use_failed' error."""
    m = re.search(r'"arguments":\s*"?(.*)', str(err), re.S)
    if not m:
        return None
    text = m.group(1).replace("\\n", "\n").replace('\\"', '"')
    return text.rstrip("\"'} \n") or None

def clean(text):
    """Remove <think>...</think> blocks that some reasoning models add."""
    return re.sub(r"<think>.*?</think>", "", text, flags=re.S).strip()

def ask(llm, system_prompt, user_prompt):
    msgs = [SystemMessage(content=system_prompt), HumanMessage(content=user_prompt)]
    try:
        return clean(llm.invoke(msgs).content)
    except BadRequestError as e:
        text = salvage(e)
        if text:
            return clean(text)
        raise

FORCE_DOWN = set()   # demo switch: LLM numbers listed here are treated as DOWN

import json, glob, base64
from email.mime.text import MIMEText
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import Flow
from google.auth.transport.requests import Request
from googleapiclient.discovery import build
from google.colab import files

os.environ["OAUTHLIB_INSECURE_TRANSPORT"] = "1"   # needed for the localhost redirect
os.environ["OAUTHLIB_RELAX_TOKEN_SCOPE"] = "1"

SCOPES = ["https://www.googleapis.com/auth/gmail.send"]
TOKEN_FILE = "token.json"
EMAIL_TO = "akshitasuresh2006@gmail.com"      # <-- your Gmail address

# 1. Find the OAuth credentials file you uploaded (or upload it now)
def find_cred_file():
    for f in glob.glob("/content/*.json"):
        if f.endswith("token.json"):
            continue
        try:
            data = json.load(open(f))
            if "installed" in data or "web" in data:
                return f
        except Exception:
            pass
    return None

CRED_FILE = find_cred_file()
if CRED_FILE is None:
    print("Upload your Gmail OAuth credentials JSON:")
    files.upload()
    CRED_FILE = find_cred_file()
assert CRED_FILE, "No OAuth client JSON found. It must be a 'Desktop app' OAuth client file."
print("Using:", CRED_FILE)

# 2. Log in to Gmail
def get_gmail_service():
    creds = None
    if os.path.exists(TOKEN_FILE):
        creds = Credentials.from_authorized_user_file(TOKEN_FILE, SCOPES)
    if creds and creds.expired and creds.refresh_token:
        creds.refresh(Request())
    if not creds or not creds.valid:
        flow = Flow.from_client_secrets_file(CRED_FILE, scopes=SCOPES,
                                             redirect_uri="http://localhost:1")
        auth_url, _ = flow.authorization_url(prompt="consent", access_type="offline")
        print("1. Open this link and approve access:\n", auth_url)
        print("\n2. After approving, the browser shows 'This site can't be reached'. That is expected.")
        print("3. Copy the FULL URL from the address bar (it starts with http://localhost:1/?code=...) and paste it below.\n")
        response_url = input("Paste the URL here: ").strip()
        flow.fetch_token(authorization_response=response_url)
        creds = flow.credentials
        open(TOKEN_FILE, "w").write(creds.to_json())
    return build("gmail", "v1", credentials=creds)

gmail = get_gmail_service()

# 3. Quick test email
def send_gmail(to, subject, body):
    msg = MIMEText(body, "plain", "utf-8")
    msg["to"] = to
    msg["subject"] = subject
    raw = base64.urlsafe_b64encode(msg.as_bytes()).decode()
    return gmail.users().messages().send(userId="me", body={"raw": raw}).execute()

send_gmail(EMAIL_TO, "Failover Arena: test email", "Gmail is connected. 🎉")
print("Test email sent to", EMAIL_TO, "- check your inbox.")

def merge_dicts(a, b):
    return {**(a or {}), **(b or {})}

class FailoverState(TypedDict):
    question: str
    down: list
    health: str
    results: Annotated[dict, merge_dicts]
    n_ok: int
    scores: dict
    judge_notes: str
    winner: int
    final_reasoning: str
    final_answer: str
    report: str
    email_to: str        # NEW: recipient (empty = don't send)
    email_status: str    # NEW: result of sending

ANSWER_PROMPT = """You are an expert answering a question.
Use chain-of-thought: think step by step and write each step as a numbered line.
Format your reply EXACTLY like this:
REASONING:
1. ...
2. ...
FINAL ANSWER:
<clear, complete, concise answer>"""

JUDGE_PROMPT = """You are an impartial judge comparing several answers to the same question.
Think step by step:
1. Work out what the correct answer should be yourself.
2. Check every reasoning step of each answer for mistakes.
3. Compare on correctness first, then completeness, then clarity.
Do NOT favour an answer because of its position or length.
Write a short comparison, then end with one score line per answer and a notes line, exactly:
SCORE_1: <integer 1-10>
SCORE_2: <integer 1-10>
(one SCORE line for every answer given)
NOTES: <one sentence on the biggest difference>"""

def health_node(state: FailoverState):
    """Ping every LLM. Anything that errors (or is in FORCE_DOWN) is marked DOWN."""
    down, lines = [], []
    for n, name in MODELS.items():
        if n in FORCE_DOWN:
            down.append(n); lines.append(f"LLM {n} ({name}): DOWN (forced for demo)"); continue
        try:
            ask(LLMS[n], "Reply with the single word OK.", "ping")
            lines.append(f"LLM {n} ({name}): UP")
        except Exception as e:
            down.append(n); lines.append(f"LLM {n} ({name}): DOWN ({type(e).__name__})")
    return {"down": down, "health": "\n".join(lines), "results": {}}

def make_llm_node(n):
    """Factory: one node per LLM. Skips if down, and survives runtime errors."""
    def llm_node(state: FailoverState):
        if n in state["down"]:
            return {"results": {n: {"ok": False, "note": "skipped (down)"}}}
        start = time.time()
        try:
            text = ask(LLMS[n], ANSWER_PROMPT, f"Question: {state['question']}")
            reasoning, _, answer = text.partition("FINAL ANSWER:")
            return {"results": {n: {"ok": True,
                                    "reasoning": reasoning.replace("REASONING:", "").strip(),
                                    "answer": answer.strip() or text,
                                    "time": round(time.time() - start, 2)}}}
        except Exception as e:
            return {"results": {n: {"ok": False, "note": f"failed while answering ({type(e).__name__})"}}}
    return llm_node

def collect_node(state: FailoverState):
    """Join point: counts how many LLMs produced a usable answer."""
    return {"n_ok": sum(1 for r in state["results"].values() if r["ok"])}

def judge_node(state: FailoverState):
    ok_ids = [n for n, r in state["results"].items() if r["ok"]]
    order = ok_ids[:]; random.shuffle(order)            # random order avoids position bias
    user = f"Question: {state['question']}\n\n"
    for i, n in enumerate(order, 1):
        r = state["results"][n]
        user += f"=== Answer {i} ===\nReasoning:\n{r['reasoning']}\nFinal answer:\n{r['answer']}\n\n"

    judge_llm = LLMS[next(n for n in [1, 3, 2] if n in ok_ids)]   # most reliable working LLM judges
    text = ask(judge_llm, JUDGE_PROMPT, user)

    scores = {}
    for i, n in enumerate(order, 1):
        m = re.search(rf"SCORE_{i}:\s*(\d+)", text)
        scores[n] = min(int(m.group(1)), 10) if m else 5
    notes = re.search(r"NOTES:\s*(.+)", text)
    best = max(scores.values())
    winner = next(n for n in [1, 3, 2] if scores.get(n) == best)   # ties go to the most reliable LLM
    r = state["results"][winner]
    return {"scores": scores, "winner": winner,
            "judge_notes": notes.group(1).strip() if notes else "No notes.",
            "final_reasoning": r["reasoning"], "final_answer": r["answer"]}

def finalize_node(state: FailoverState):
    winner, scores = state["winner"], state.get("scores") or {}
    reasoning, answer = state.get("final_reasoning", ""), state.get("final_answer", "")
    note = "Judge compared the working LLMs." if scores else "Only one LLM answered, so no comparison was needed."
    if not winner:                                       # single-answer path
        winner = next(n for n, r in state["results"].items() if r["ok"])
        r = state["results"][winner]
        reasoning, answer = r["reasoning"], r["answer"]
    lines = []
    for n, name in MODELS.items():
        r = state["results"][n]
        detail = (f"answered in {r['time']}s" + (f", score {scores[n]}/10" if n in scores else "")
                  if r["ok"] else r["note"])
        lines.append(f"  LLM {n} ({name}): {detail}")
    report = (f"--- Health check ---\n{state['health']}\n\n"
              f"--- Results ---\n" + "\n".join(lines) + "\n\n"
              f"{note} {state.get('judge_notes', '')}\n"
              f"WINNER: LLM {winner} ({MODELS[winner]})\n\n"
              f"--- Reasoning ---\n{reasoning}\n\n=== BEST ANSWER ===\n{answer}")
    return {"winner": winner, "final_reasoning": reasoning, "final_answer": answer, "report": report}

def fail_node(state: FailoverState):
    return {"report": f"--- Health check ---\n{state['health']}\n\n"
                      "No LLM could answer right now. Check your API key, model names and rate limits, then try again."}

def email_node(state: FailoverState):
    """Send the final report to Gmail. A failure here never crashes the workflow."""
    try:
        subject = f"LLM Arena result: {state['question'][:60]}"
        body = (f"Question:\n{state['question']}\n\n"
                f"{'=' * 50}\n{state['report']}\n\n"
                f"-- Sent by your LangGraph Failover Arena")
        send_gmail(state["email_to"], subject, body)
        return {"email_status": f"Sent to {state['email_to']}"}
    except Exception as e:
        return {"email_status": f"Email failed ({type(e).__name__}: {e})"}

def route_after_finalize(state: FailoverState) -> str:
    """Send an email only if a recipient address is set."""
    return "email" if state.get("email_to") else END

def route_after_collect(state: FailoverState) -> str:
    """0 answers -> fail.  1 answer -> finalize directly.  2+ answers -> judge them."""
    if state["n_ok"] == 0:
        return "fail"
    if state["n_ok"] == 1:
        return "finalize"
    return "judge"

from langgraph.graph import StateGraph, START, END

b = StateGraph(FailoverState)

b.add_node("health_check", health_node)
b.add_node("llm_1", make_llm_node(1))
b.add_node("llm_2", make_llm_node(2))
b.add_node("llm_3", make_llm_node(3))
b.add_node("collect", collect_node)
b.add_node("judge", judge_node)
b.add_node("finalize", finalize_node)
b.add_node("email", email_node)
b.add_node("fail", fail_node)

b.add_edge(START, "health_check")
for n in ["llm_1", "llm_2", "llm_3"]:
    b.add_edge("health_check", n)
b.add_edge(["llm_1", "llm_2", "llm_3"], "collect")
b.add_conditional_edges("collect", route_after_collect, ["fail", "finalize", "judge"])
b.add_edge("judge", "finalize")
b.add_conditional_edges("finalize", route_after_finalize, ["email", END])   # NEW route
b.add_edge("email", END)
b.add_edge("fail", END)

failover = b.compile()

from IPython.display import Image, display
try:
    display(Image(failover.get_graph().draw_mermaid_png()))
except Exception:
    print(failover.get_graph().draw_mermaid())

import matplotlib.pyplot as plt

def run_failover(question: str, send_email: bool = True):
    state = {"question": question, "down": [], "health": "", "results": {}, "n_ok": 0,
             "scores": {}, "judge_notes": "", "winner": 0,
             "final_reasoning": "", "final_answer": "", "report": "",
             "email_to": EMAIL_TO if send_email else "", "email_status": ""}
    print("Workflow trace:")
    for step in failover.stream(state, stream_mode="updates"):
        for node, update in step.items():
            extra = ""
            if node == "health_check": extra = f" -> down = {update['down'] or 'none'}"
            if node == "collect":      extra = f" -> {update['n_ok']} LLM(s) answered"
            if node == "judge":        extra = f" -> scores = {update['scores']}"
            if node == "email":        extra = f" -> {update['email_status']}"
            print(f"  ➡ {node}{extra}")
            for k, v in update.items():
                state[k] = merge_dicts(state[k], v) if k == "results" else v
    print("\n" + "=" * 60)
    print(state["report"])
    if state["email_status"]:
        print("\n📧", state["email_status"])

    ok = {n: r for n, r in state["results"].items() if r["ok"]}
    if ok:
        labels = [f"LLM {n}" for n in ok]
        fig, ax = plt.subplots(1, 2, figsize=(10, 3.5))
        ax[0].bar(labels, [state["scores"].get(n, 0) for n in ok], color="tab:blue")
        ax[0].set_ylim(0, 10.5); ax[0].set_title("Judge score (0 = not judged)")
        ax[1].bar(labels, [r["time"] for r in ok.values()], color="tab:orange")
        ax[1].set_title("Response time (s)")
        plt.tight_layout(); plt.show()
    return state

Q = "If 5 machines make 5 widgets in 5 minutes, how long do 100 machines take to make 100 widgets?"

print("##### Scenario 1: LLM 1 works, LLM 2 doesn't, LLM 3 should #####")
FORCE_DOWN = {2}
run_failover(Q)

print("\n\n##### Scenario 2: LLM 1 doesn't work, LLM 3 should #####")
FORCE_DOWN = {1, 2}
run_failover(Q)

FORCE_DOWN = set()
run_failover("Explain the difference between a process and a thread with one example.")