# -*- coding: utf-8 -*-
"""Cot 2 LLMs Comparision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mIHL-qYjWjkPEsOgO39pZcEN6qtcTo7x
"""

!pip install -q langgraph langchain-groq langchain-core matplotlib

import os, re, time, random, getpass
from typing import TypedDict
from groq import Groq, BadRequestError
from langchain_groq import ChatGroq
from langchain_core.messages import SystemMessage, HumanMessage

# API key: Colab secret first (change "Project" to your secret's name), otherwise type it
try:
    from google.colab import userdata
    key = userdata.get("Project").strip()
except Exception:
    key = getpass.getpass("Enter your Groq API key (starts with gsk_): ").strip()
os.environ["GROQ_API_KEY"] = key

# Ask Groq which models your key can use
available = [m.id for m in Groq().models.list().data]
skip = ["whisper", "tts", "guard", "embed"]
chat_models = [m for m in available if not any(x in m.lower() for x in skip)]
print("Chat models available:", chat_models)

# llama models first: gpt-oss models can trigger the tool_use_failed error
pref_a = ["llama-3.3-70b-versatile", "llama-3.1-8b-instant", "openai/gpt-oss-120b"]
pref_b = ["llama-3.1-8b-instant", "llama-3.3-70b-versatile", "openai/gpt-oss-20b", "openai/gpt-oss-120b"]

MODEL_A = next((m for m in pref_a if m in chat_models), chat_models[0])
MODEL_B = next((m for m in pref_b if m in chat_models and m != MODEL_A), None)

llm_a = ChatGroq(model=MODEL_A, temperature=0.2)
if MODEL_B is None:
    print("Only one model available: Model B will reuse it with a higher temperature.")
    MODEL_B = MODEL_A
    llm_b = ChatGroq(model=MODEL_B, temperature=0.9)
else:
    llm_b = ChatGroq(model=MODEL_B, temperature=0.2)

def salvage(err):
    """Recover the model's text from a gpt-oss 'tool_use_failed' error."""
    m = re.search(r'"arguments":\s*"?(.*)', str(err), re.S)
    if not m:
        return None
    text = m.group(1).replace("\\n", "\n").replace('\\"', '"')
    return text.rstrip("\"'} \n") or None

def ask(llm, system_prompt, user_prompt):
    msgs = [SystemMessage(content=system_prompt), HumanMessage(content=user_prompt)]
    try:
        return llm.invoke(msgs).content.strip()
    except BadRequestError as e:
        text = salvage(e)
        if text:
            return text.strip()
        return llm.invoke(msgs).content.strip()   # one retry

print("\nModel A:", MODEL_A)
print("Model B:", MODEL_B)
print("Test A:", ask(llm_a, "You are helpful.", "Say hello in one short sentence."))
print("Test B:", ask(llm_b, "You are helpful.", "Say hello in one short sentence."))

class ArenaState(TypedDict):
    question: str
    task_type: str        # math | coding | factual | reasoning | creative
    criteria: str         # what a good answer must contain (from analyze node)
    # Contender A
    reasoning_a: str
    answer_a: str
    time_a: float
    # Contender B
    reasoning_b: str
    answer_b: str
    time_b: float
    # Judge
    score_a: int
    score_b: int
    judge_notes: str
    winner: str           # A | B | MERGED
    # Output
    final_reasoning: str
    final_answer: str
    report: str

ANALYZE_PROMPT = """You are a question analyst for an LLM comparison app.
Think step by step:
1. Restate what is being asked.
2. Decide the task type: math, coding, factual, reasoning or creative.
3. List 3 short criteria a really good answer must meet.
Write your steps briefly, then end with exactly these two lines:
TASK_TYPE: <one word>
CRITERIA: <criterion 1>; <criterion 2>; <criterion 3>"""

CONTENDER_PROMPT = """You are an expert answering a question. Evaluation criteria for a good answer: {criteria}
Use chain-of-thought: think step by step, writing each step as a numbered line.
Format your reply EXACTLY like this:
REASONING:
1. ...
2. ...
FINAL ANSWER:
<clear, complete, concise answer>"""

JUDGE_PROMPT = """You are an impartial judge comparing two answers to the same question.
Criteria: {criteria}
Think step by step:
1. Work out what the correct answer should be yourself.
2. Check every reasoning step of Answer 1 for mistakes.
3. Check every reasoning step of Answer 2 for mistakes.
4. Compare on correctness first, then completeness, then clarity.
Do NOT favour an answer because of its position or length.
Write a short comparison, then end with exactly these three lines:
SCORE_1: <integer 1-10>
SCORE_2: <integer 1-10>
NOTES: <one sentence on the biggest difference>"""

MERGE_PROMPT = """Two answers to the same question scored almost equally.
Think step by step:
1. List what Answer 1 does well and where it is weak.
2. List what Answer 2 does well and where it is weak.
3. Build one improved answer that keeps the strengths and fixes the weaknesses.
Format your reply EXACTLY like this:
REASONING:
1. ...
FINAL ANSWER:
<the improved answer>"""

def parse_sections(text):
    reasoning, _, answer = text.partition("FINAL ANSWER:")
    return reasoning.replace("REASONING:", "").strip(), (answer.strip() or text)

def analyze_node(state: ArenaState):
    text = ask(llm_a, ANALYZE_PROMPT, state["question"])
    t = re.search(r"TASK_TYPE:\s*(\w+)", text, re.I)
    c = re.search(r"CRITERIA:\s*(.+)", text, re.I)
    return {"task_type": t.group(1).lower() if t else "reasoning",
            "criteria": c.group(1).strip() if c else "correct; complete; clear"}

def make_contender(llm, tag):
    """Factory: builds one contender node. Both run in parallel and write to different state keys."""
    def contender_node(state: ArenaState):
        start = time.time()
        text = ask(llm, CONTENDER_PROMPT.format(criteria=state["criteria"]),
                   f"Question: {state['question']}")
        reasoning, answer = parse_sections(text)
        return {f"reasoning_{tag}": reasoning, f"answer_{tag}": answer,
                f"time_{tag}": round(time.time() - start, 2)}
    return contender_node

model_a_node = make_contender(llm_a, "a")
model_b_node = make_contender(llm_b, "b")

def judge_node(state: ArenaState):
    # Show the answers in random order to avoid position bias
    a_first = random.random() < 0.5
    first = ("A", state["reasoning_a"], state["answer_a"]) if a_first else ("B", state["reasoning_b"], state["answer_b"])
    second = ("B", state["reasoning_b"], state["answer_b"]) if a_first else ("A", state["reasoning_a"], state["answer_a"])

    user = (f"Question: {state['question']}\n\n"
            f"=== Answer 1 ===\nReasoning:\n{first[1]}\nFinal answer:\n{first[2]}\n\n"
            f"=== Answer 2 ===\nReasoning:\n{second[1]}\nFinal answer:\n{second[2]}")
    text = ask(llm_a, JUDGE_PROMPT.format(criteria=state["criteria"]), user)

    s1 = re.search(r"SCORE_1:\s*(\d+)", text)
    s2 = re.search(r"SCORE_2:\s*(\d+)", text)
    n = re.search(r"NOTES:\s*(.+)", text)
    score1 = min(int(s1.group(1)), 10) if s1 else 5
    score2 = min(int(s2.group(1)), 10) if s2 else 5

    # Map the scores back to A and B
    score_a, score_b = (score1, score2) if first[0] == "A" else (score2, score1)
    update = {"score_a": score_a, "score_b": score_b,
              "judge_notes": n.group(1).strip() if n else "No notes."}

    if abs(score_a - score_b) >= 2:          # clear winner: keep it now
        w = "A" if score_a > score_b else "B"
        update.update({"winner": w,
                       "final_reasoning": state[f"reasoning_{w.lower()}"],
                       "final_answer": state[f"answer_{w.lower()}"]})
    return update

def merge_node(state: ArenaState):
    user = (f"Question: {state['question']}\n\n"
            f"=== Answer 1 ===\n{state['reasoning_a']}\n{state['answer_a']}\n\n"
            f"=== Answer 2 ===\n{state['reasoning_b']}\n{state['answer_b']}\n\n"
            f"Judge's note: {state['judge_notes']}")
    text = ask(llm_a, MERGE_PROMPT, user)
    reasoning, answer = parse_sections(text)
    return {"winner": "MERGED", "final_reasoning": reasoning, "final_answer": answer}

def finalize_node(state: ArenaState):
    who = {"A": f"Model A ({MODEL_A})", "B": f"Model B ({MODEL_B})",
           "MERGED": "Merged answer (scores were too close)"}[state["winner"]]
    report = (f"Task type : {state['task_type']}\n"
              f"Criteria  : {state['criteria']}\n\n"
              f"Model A ({MODEL_A}): score {state['score_a']}/10, {state['time_a']}s\n"
              f"Model B ({MODEL_B}): score {state['score_b']}/10, {state['time_b']}s\n"
              f"Judge says: {state['judge_notes']}\n\n"
              f"WINNER: {who}\n\n"
              f"--- Reasoning ---\n{state['final_reasoning']}\n\n"
              f"=== BEST ANSWER ===\n{state['final_answer']}")
    return {"report": report}

def route_after_judge(state: ArenaState) -> str:
    """Clear winner (score gap >= 2) -> finalize. Too close to call -> merge both answers first."""
    if abs(state["score_a"] - state["score_b"]) >= 2:
        return "finalize"
    return "merge"

from langgraph.graph import StateGraph, START, END

builder = StateGraph(ArenaState)

builder.add_node("analyze", analyze_node)
builder.add_node("model_a", model_a_node)
builder.add_node("model_b", model_b_node)
builder.add_node("judge", judge_node)
builder.add_node("merge", merge_node)
builder.add_node("finalize", finalize_node)

builder.add_edge(START, "analyze")
builder.add_edge("analyze", "model_a")            # fan-out: both run in parallel
builder.add_edge("analyze", "model_b")
builder.add_edge(["model_a", "model_b"], "judge")  # join: judge waits for both
builder.add_conditional_edges("judge", route_after_judge, ["merge", "finalize"])
builder.add_edge("merge", "finalize")
builder.add_edge("finalize", END)

arena = builder.compile()

from IPython.display import Image, display
try:
    display(Image(arena.get_graph().draw_mermaid_png()))
except Exception:
    print(arena.get_graph().draw_mermaid())   # paste at mermaid.live to see the diagram

import matplotlib.pyplot as plt

def run_arena(question: str):
    state = {"question": question, "task_type": "", "criteria": "",
             "reasoning_a": "", "answer_a": "", "time_a": 0.0,
             "reasoning_b": "", "answer_b": "", "time_b": 0.0,
             "score_a": 0, "score_b": 0, "judge_notes": "", "winner": "",
             "final_reasoning": "", "final_answer": "", "report": ""}
    print("Workflow trace:")
    for step in arena.stream(state, stream_mode="updates"):
        for node, update in step.items():
            extra = ""
            if node == "analyze": extra = f" -> {update['task_type']}"
            if node == "judge":   extra = f" -> A={update['score_a']}  B={update['score_b']}"
            print(f"  ➡ {node}{extra}")
            state.update(update)
    print("\n" + "=" * 60)
    print(state["report"])

    # Comparison chart
    fig, ax = plt.subplots(1, 2, figsize=(11, 3.8))
    labels = [f"A\n{MODEL_A}", f"B\n{MODEL_B}"]
    bars = ax[0].bar(labels, [state["score_a"], state["score_b"]], color=["tab:blue", "tab:orange"])
    ax[0].set_ylim(0, 10.5); ax[0].set_title("Judge score (out of 10)")
    for b, v in zip(bars, [state["score_a"], state["score_b"]]):
        ax[0].text(b.get_x() + b.get_width() / 2, v + 0.2, v, ha="center")
    bars = ax[1].bar(labels, [state["time_a"], state["time_b"]], color=["tab:blue", "tab:orange"])
    ax[1].set_title("Response time (seconds)")
    for b, v in zip(bars, [state["time_a"], state["time_b"]]):
        ax[1].text(b.get_x() + b.get_width() / 2, v + 0.05, f"{v}s", ha="center")
    plt.tight_layout(); plt.show()
    return state

result = run_arena("If 5 machines make 5 widgets in 5 minutes, how long do 100 machines take to make 100 widgets?")

run_arena("Explain the difference between supervised and unsupervised learning with one example each.")
run_arena("Write a Python function that returns the second largest number in a list without sorting it.")
run_arena("Which is better for a student project: building a CNN from scratch or using transfer learning? Justify.")