# -*- coding: utf-8 -*-
"""GAN Proj.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ekfAe_PQe9Tu6D5Hz3G-4LhgEbsyxhjJ
"""

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import layers, models

print("TensorFlow:", tf.__version__)
print("GPU:", tf.config.list_physical_devices("GPU"))

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.fashion_mnist.load_data()
class_names = ["T-shirt", "Trouser", "Pullover", "Dress", "Coat",
               "Sandal", "Shirt", "Sneaker", "Bag", "Ankle boot"]

# Scale pixels to [-1, 1] (matches the generator's tanh output)
x_train_n = ((x_train.astype("float32") - 127.5) / 127.5)[..., None]
x_test_n = ((x_test.astype("float32") - 127.5) / 127.5)[..., None]
print("Train:", x_train_n.shape, "| Test:", x_test_n.shape)

fig, ax = plt.subplots(2, 2, figsize=(13, 9))

# 1. Class balance
counts = np.bincount(y_train)
ax[0, 0].bar(class_names, counts, color="tab:blue")
ax[0, 0].set_title("Images per class (train)")
ax[0, 0].tick_params(axis="x", rotation=45)

# 2. Pixel intensity distribution
ax[0, 1].hist(x_train[:5000].ravel(), bins=50, color="tab:purple")
ax[0, 1].set_title("Pixel intensity distribution (0-255)")

# 3. Mean image of each class (shown as a strip)
means = np.hstack([x_train[y_train == c].mean(axis=0) for c in range(10)])
ax[1, 0].imshow(means, cmap="gray"); ax[1, 0].axis("off")
ax[1, 0].set_title("Average image per class")

# 4. Sample real images
sample = np.vstack([np.hstack([x_train[y_train == c][i] for c in range(10)]) for i in range(3)])
ax[1, 1].imshow(sample, cmap="gray"); ax[1, 1].axis("off")
ax[1, 1].set_title("Real samples (one column per class)")

plt.tight_layout(); plt.show()

NOISE = 100

def build_generator():
    return models.Sequential([
        layers.Input(shape=(NOISE,)),
        layers.Dense(7 * 7 * 256, use_bias=False),
        layers.BatchNormalization(), layers.LeakyReLU(0.2),
        layers.Reshape((7, 7, 256)),
        layers.Conv2DTranspose(128, 5, strides=1, padding="same", use_bias=False),
        layers.BatchNormalization(), layers.LeakyReLU(0.2),
        layers.Conv2DTranspose(64, 5, strides=2, padding="same", use_bias=False),   # 14x14
        layers.BatchNormalization(), layers.LeakyReLU(0.2),
        layers.Conv2DTranspose(1, 5, strides=2, padding="same", activation="tanh"), # 28x28
    ], name="generator")

def build_discriminator():
    return models.Sequential([
        layers.Input(shape=(28, 28, 1)),
        layers.Conv2D(64, 5, strides=2, padding="same"),
        layers.LeakyReLU(0.2), layers.Dropout(0.3),
        layers.Conv2D(128, 5, strides=2, padding="same"),
        layers.LeakyReLU(0.2), layers.Dropout(0.3),
        layers.Flatten(),
        layers.Dense(1),   # raw logit: real vs fake
    ], name="discriminator")

generator = build_generator()
discriminator = build_discriminator()
generator.summary()
discriminator.summary()

# Image from the generator before any training (pure noise)
untrained = generator(tf.random.normal([1, NOISE]), training=False)
plt.imshow(untrained[0, :, :, 0], cmap="gray"); plt.axis("off")
plt.title("Generator output BEFORE training"); plt.show()

BATCH = 256
EPOCHS = 15

train_ds = (tf.data.Dataset.from_tensor_slices(x_train_n)
            .shuffle(60000).batch(BATCH, drop_remainder=True)
            .prefetch(tf.data.AUTOTUNE))

bce = tf.keras.losses.BinaryCrossentropy(from_logits=True)
g_opt = tf.keras.optimizers.Adam(2e-4, beta_1=0.5)
d_opt = tf.keras.optimizers.Adam(2e-4, beta_1=0.5)

@tf.function
def train_step(real_images):
    noise = tf.random.normal([BATCH, NOISE])
    with tf.GradientTape() as g_tape, tf.GradientTape() as d_tape:
        fake_images = generator(noise, training=True)
        real_out = discriminator(real_images, training=True)
        fake_out = discriminator(fake_images, training=True)

        g_loss = bce(tf.ones_like(fake_out), fake_out)
        # label smoothing (0.9) keeps the discriminator from becoming overconfident
        d_loss = (bce(tf.ones_like(real_out) * 0.9, real_out) +
                  bce(tf.zeros_like(fake_out), fake_out))

    g_grads = g_tape.gradient(g_loss, generator.trainable_variables)
    d_grads = d_tape.gradient(d_loss, discriminator.trainable_variables)
    g_opt.apply_gradients(zip(g_grads, generator.trainable_variables))
    d_opt.apply_gradients(zip(d_grads, discriminator.trainable_variables))

    real_acc = tf.reduce_mean(tf.cast(real_out > 0, tf.float32))
    fake_acc = tf.reduce_mean(tf.cast(fake_out < 0, tf.float32))
    return g_loss, d_loss, real_acc, fake_acc

import time

fixed_noise = tf.random.normal([16, NOISE], seed=7)   # same noise every epoch to track progress
snap_epochs = [1, 3, 5, 10, 15]
snapshots = {}
hist = {"g_loss": [], "d_loss": [], "real_acc": [], "fake_acc": []}

for epoch in range(1, EPOCHS + 1):
    t0 = time.time()
    m = []
    for batch in train_ds:
        m.append([v.numpy() for v in train_step(batch)])
    m = np.mean(m, axis=0)
    for k, v in zip(hist.keys(), m):
        hist[k].append(float(v))
    if epoch in snap_epochs:
        snapshots[epoch] = generator(fixed_noise, training=False).numpy()
    print(f"Epoch {epoch:2d}/{EPOCHS} | G loss {m[0]:.3f} | D loss {m[1]:.3f} | "
          f"D acc real {m[2]:.0%} fake {m[3]:.0%} | {time.time() - t0:.1f}s")

generator.save("fashion_generator.keras")

def tile(imgs, n=4):
    imgs = (imgs[..., 0] + 1) / 2          # back to [0, 1]
    return imgs.reshape(n, n, 28, 28).transpose(0, 2, 1, 3).reshape(n * 28, n * 28)

fig, ax = plt.subplots(1, 3, figsize=(17, 4.5))
ep = range(1, EPOCHS + 1)

ax[0].plot(ep, hist["g_loss"], marker="o", label="Generator", color="tab:blue")
ax[0].plot(ep, hist["d_loss"], marker="o", label="Discriminator", color="tab:red")
ax[0].set_title("Generator vs Discriminator loss"); ax[0].set_xlabel("Epoch"); ax[0].legend()

ax[1].plot(ep, hist["real_acc"], marker="o", label="Real images correctly identified", color="tab:green")
ax[1].plot(ep, hist["fake_acc"], marker="o", label="Fake images caught", color="tab:orange")
ax[1].axhline(0.5, color="k", linestyle="--", label="Ideal balance (50%)")
ax[1].set_ylim(0, 1.05); ax[1].set_title("Discriminator accuracy")
ax[1].set_xlabel("Epoch"); ax[1].legend(fontsize=8)

ax[2].plot(ep, np.array(hist["g_loss"]) / np.array(hist["d_loss"]), marker="o", color="tab:purple")
ax[2].set_title("Loss ratio (G / D)"); ax[2].set_xlabel("Epoch")
plt.tight_layout(); plt.show()

# How the generated images improve over epochs
fig, axes = plt.subplots(1, len(snapshots), figsize=(4 * len(snapshots), 4.3))
for a, (e, imgs) in zip(axes, snapshots.items()):
    a.imshow(tile(imgs), cmap="gray"); a.axis("off"); a.set_title(f"Epoch {e}")
plt.suptitle("Generator progress (same noise, different epochs)", fontsize=14)
plt.tight_layout(); plt.show()

noise = tf.random.normal([64, NOISE])
fake = generator(noise, training=False).numpy()
real = x_test_n[np.random.choice(len(x_test_n), 64, replace=False)]

def tile8(imgs):
    return ((imgs[..., 0] + 1) / 2).reshape(8, 8, 28, 28).transpose(0, 2, 1, 3).reshape(224, 224)

fig, ax = plt.subplots(1, 2, figsize=(13, 6.5))
ax[0].imshow(tile8(real), cmap="gray"); ax[0].axis("off"); ax[0].set_title("REAL images", fontsize=14)
ax[1].imshow(tile8(fake), cmap="gray"); ax[1].axis("off"); ax[1].set_title("GENERATED (fake) images", fontsize=14)
plt.tight_layout(); plt.show()

steps = 10
z1 = tf.random.normal([1, NOISE]); z2 = tf.random.normal([1, NOISE])
alphas = np.linspace(0, 1, steps)[:, None].astype("float32")
z = (1 - alphas) * z1.numpy() + alphas * z2.numpy()
morph = generator(z, training=False).numpy()

plt.figure(figsize=(16, 2.5))
for i in range(steps):
    plt.subplot(1, steps, i + 1)
    plt.imshow((morph[i, :, :, 0] + 1) / 2, cmap="gray"); plt.axis("off")
plt.suptitle("Smooth morphing through the latent space", fontsize=13)
plt.show()

n = 1000
real_scores = tf.sigmoid(discriminator(x_test_n[:n], training=False)).numpy().ravel()
fake_imgs = generator(tf.random.normal([n, NOISE]), training=False)
fake_scores = tf.sigmoid(discriminator(fake_imgs, training=False)).numpy().ravel()

plt.figure(figsize=(8, 4.5))
plt.hist(real_scores, bins=30, alpha=0.6, label="Real images", color="tab:green")
plt.hist(fake_scores, bins=30, alpha=0.6, label="Fake images", color="tab:red")
plt.axvline(0.5, color="k", linestyle="--")
plt.title("Discriminator's probability that an image is REAL")
plt.xlabel("P(real)"); plt.legend(); plt.show()

print(f"Average P(real) for real images: {real_scores.mean():.2f}")
print(f"Average P(real) for fake images: {fake_scores.mean():.2f}")

from google.colab import files

imgs = generator(tf.random.normal([100, NOISE]), training=False).numpy()
sheet = ((imgs[..., 0] + 1) / 2).reshape(10, 10, 28, 28).transpose(0, 2, 1, 3).reshape(280, 280)
plt.figure(figsize=(7, 7)); plt.imshow(sheet, cmap="gray"); plt.axis("off")
plt.title("100 AI-generated fashion items"); plt.savefig("generated_sheet.png", dpi=200, bbox_inches="tight")
plt.show()

files.download("generated_sheet.png")
files.download("fashion_generator.keras")