# -*- coding: utf-8 -*-
"""Rnn Proj.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XjR-8G1Zc8k8y4Ui_czFBrI2Tf7ACHgg
"""

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.sequence import pad_sequences

print("TensorFlow:", tf.__version__)
print("GPU:", tf.config.list_physical_devices("GPU"))

VOCAB = 10000     # keep the 10,000 most frequent words
MAXLEN = 200      # each review is cut/padded to 200 words

(x_train_raw, y_train), (x_test_raw, y_test) = imdb.load_data(num_words=VOCAB)
print("Train reviews:", len(x_train_raw), "| Test reviews:", len(x_test_raw))

from collections import Counter

word_index = imdb.get_word_index()
index_to_word = {v + 3: k for k, v in word_index.items()}
index_to_word.update({0: "<PAD>", 1: "<START>", 2: "<UNK>", 3: "<UNK>"})

def decode(seq):
    return " ".join(index_to_word.get(i, "?") for i in seq if i > 3)

stop = set("the a an and of to is in it i this that was as for with but on his her he she "
           "they you are be at by from have has had not or one all so there their what "
           "who just its if out when which about up more can no my were we them than "
           "me been into do would very some like movie film br".split())

fig, ax = plt.subplots(2, 2, figsize=(14, 9))

# 1. Class balance
vals, cnts = np.unique(y_train, return_counts=True)
ax[0, 0].bar(["Negative", "Positive"], cnts, color=["tab:red", "tab:green"])
ax[0, 0].set_title("Class balance (train set)")
for i, c in enumerate(cnts):
    ax[0, 0].text(i, c + 200, c, ha="center")

# 2. Review length distribution
lengths = [len(x) for x in x_train_raw]
ax[0, 1].hist(lengths, bins=50, color="tab:blue", alpha=0.8)
ax[0, 1].axvline(MAXLEN, color="red", linestyle="--", label=f"cut-off = {MAXLEN}")
ax[0, 1].set_title("Review length (words)"); ax[0, 1].legend()

# 3 & 4. Top words per sentiment
for a, label, name, col in [(ax[1, 0], 1, "Positive", "tab:green"),
                            (ax[1, 1], 0, "Negative", "tab:red")]:
    c = Counter()
    for seq, y in zip(x_train_raw[:5000], y_train[:5000]):
        if y == label:
            c.update(w for w in decode(seq).split() if w not in stop and len(w) > 2)
    words, counts = zip(*c.most_common(12))
    a.barh(words[::-1], counts[::-1], color=col)
    a.set_title(f"Top words in {name} reviews")

plt.tight_layout(); plt.show()

print("Sample positive review:\n", decode(x_train_raw[np.where(y_train == 1)[0][0]])[:400])
print("\nSample negative review:\n", decode(x_train_raw[np.where(y_train == 0)[0][0]])[:400])

x_train = pad_sequences(x_train_raw, maxlen=MAXLEN)   # pads at the start by default
x_test = pad_sequences(x_test_raw, maxlen=MAXLEN)
print("Shape:", x_train.shape)

def build_model(kind):
    m = models.Sequential([
        layers.Input(shape=(MAXLEN,)),
        layers.Embedding(VOCAB, 64),
    ])
    if kind == "SimpleRNN":
        m.add(layers.SimpleRNN(64))
    elif kind == "LSTM":
        m.add(layers.LSTM(64))
    elif kind == "BiLSTM":
        m.add(layers.Bidirectional(layers.LSTM(64)))
    m.add(layers.Dropout(0.4))
    m.add(layers.Dense(32, activation="relu"))
    m.add(layers.Dense(1, activation="sigmoid"))
    m.compile(optimizer=tf.keras.optimizers.Adam(1e-3),
              loss="binary_crossentropy", metrics=["accuracy"])
    return m

lstm_model = build_model("LSTM")
lstm_model.summary()

EPOCHS = 4
kinds = ["SimpleRNN", "LSTM", "BiLSTM"]
trained, histories = {}, {}

for k in kinds:
    print(f"\n===== Training {k} =====")
    m = build_model(k)
    histories[k] = m.fit(x_train, y_train, epochs=EPOCHS, batch_size=128,
                         validation_split=0.2, verbose=1)
    trained[k] = m

trained["LSTM"].save("sentiment_lstm.keras")

colors = {"SimpleRNN": "tab:red", "LSTM": "tab:blue", "BiLSTM": "tab:green"}
fig, ax = plt.subplots(1, 3, figsize=(17, 4.5))

for k in kinds:
    h = histories[k].history
    ax[0].plot(h["val_accuracy"], marker="o", label=k, color=colors[k])
    ax[1].plot(h["val_loss"], marker="o", label=k, color=colors[k])
ax[0].set_title("Validation accuracy"); ax[0].set_xlabel("Epoch"); ax[0].legend()
ax[1].set_title("Validation loss"); ax[1].set_xlabel("Epoch"); ax[1].legend()

h = histories["LSTM"].history
ax[2].plot(h["accuracy"], marker="o", label="Train acc")
ax[2].plot(h["val_accuracy"], marker="o", label="Val acc")
ax[2].plot(h["loss"], marker="s", linestyle="--", label="Train loss")
ax[2].plot(h["val_loss"], marker="s", linestyle="--", label="Val loss")
ax[2].set_title("LSTM: train vs validation"); ax[2].set_xlabel("Epoch"); ax[2].legend()

plt.tight_layout(); plt.show()

test_acc = {}
for k in kinds:
    loss, acc = trained[k].evaluate(x_test, y_test, verbose=0)
    test_acc[k] = acc

plt.figure(figsize=(6, 4))
bars = plt.bar(test_acc.keys(), test_acc.values(), color=[colors[k] for k in kinds])
for b, v in zip(bars, test_acc.values()):
    plt.text(b.get_x() + b.get_width() / 2, v + 0.01, f"{v:.1%}", ha="center")
plt.ylim(0, 1.05); plt.title("Test accuracy comparison"); plt.ylabel("Accuracy")
plt.show()

from sklearn.metrics import confusion_matrix, classification_report, roc_curve, auc

best = trained["LSTM"]
y_prob = best.predict(x_test, batch_size=256, verbose=0).ravel()
y_pred = (y_prob > 0.5).astype(int)

print(classification_report(y_test, y_pred, target_names=["Negative", "Positive"]))

fig, ax = plt.subplots(1, 3, figsize=(17, 4.5))

cm = confusion_matrix(y_test, y_pred)
ax[0].imshow(cm, cmap="Blues")
ax[0].set_xticks([0, 1]); ax[0].set_xticklabels(["Negative", "Positive"])
ax[0].set_yticks([0, 1]); ax[0].set_yticklabels(["Negative", "Positive"])
for i in range(2):
    for j in range(2):
        ax[0].text(j, i, cm[i, j], ha="center", va="center", fontsize=16,
                   color="white" if cm[i, j] > cm.max() / 2 else "black")
ax[0].set_title("Confusion matrix"); ax[0].set_xlabel("Predicted"); ax[0].set_ylabel("Actual")

fpr, tpr, _ = roc_curve(y_test, y_prob)
ax[1].plot(fpr, tpr, color="tab:red", label=f"AUC = {auc(fpr, tpr):.3f}")
ax[1].plot([0, 1], [0, 1], "k--")
ax[1].set_title("ROC curve"); ax[1].set_xlabel("False positive rate")
ax[1].set_ylabel("True positive rate"); ax[1].legend()

ax[2].hist(y_prob[y_test == 0], bins=25, alpha=0.6, label="Actual negative", color="tab:red")
ax[2].hist(y_prob[y_test == 1], bins=25, alpha=0.6, label="Actual positive", color="tab:green")
ax[2].axvline(0.5, color="k", linestyle="--")
ax[2].set_title("Predicted probability of positive"); ax[2].legend()

plt.tight_layout(); plt.show()

import re

def predict_review(text, model=trained["LSTM"]):
    words = re.sub(r"[^a-z' ]", "", text.lower()).split()
    seq = [1]  # start token
    for w in words:
        idx = word_index.get(w, -1) + 3
        seq.append(idx if 3 < idx < VOCAB else 2)
    seq = pad_sequences([seq], maxlen=MAXLEN)
    p = float(model.predict(seq, verbose=0)[0][0])
    label = "POSITIVE" if p > 0.5 else "NEGATIVE"
    conf = p if p > 0.5 else 1 - p
    print(f"{label} ({conf:.0%}) -> {text}")

predict_review("This movie was absolutely fantastic, I loved the acting and the story")
predict_review("Terrible film, boring plot and the worst acting I have ever seen")
predict_review("It was okay, some good parts but a bit too long")

# Try your own:
predict_review(input("Type your own review: "))